from __future__ import annotations

import json

from footprint.scanner import ScanResult


def format_json(results: list[ScanResult]) -> str:
    data = []
    for r in results:
        matches = []
        for m in r.matches:
            entry: dict[str, object] = {
                "pattern": m.pattern,
                "category": m.category,
                "stack": m.stack,
                "line": m.line,
                "source": m.source,
            }
            if m.transitive:
                entry["transitive"] = True
            matches.append(entry)
        data.append(
            {
                "file": r.file,
                "categories": r.categories,
                "matches": matches,
            }
        )
    return json.dumps(data, indent=2)


def format_flat(results: list[ScanResult]) -> str:
    return "\n".join(r.file for r in results)


def format_markdown(results: list[ScanResult], repo_root: str = "") -> str:
    from datetime import datetime, timezone

    lines: list[str] = []
    lines.append("# Network Footprint Report")
    lines.append("")
    if repo_root:
        lines.append(f"Scanned: `{repo_root}`  ")
    lines.append(f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")  # noqa: UP017
    lines.append("")

    # Group results by category
    category_order = ["route_definition", "network_call", "devops"]
    category_labels = {
        "route_definition": "Route Definitions",
        "network_call": "Network Calls",
        "devops": "DevOps",
    }

    # Collect all categories present (preserve order, add unknowns at end)
    all_cats: list[str] = []
    seen_cats: set[str] = set()
    for cat in category_order:
        all_cats.append(cat)
        seen_cats.add(cat)
    for r in results:
        for c in r.categories:
            if c not in seen_cats:
                all_cats.append(c)
                seen_cats.add(c)

    for cat in all_cats:
        # Files that have at least one match in this category
        cat_results = [
            (r, [m for m in r.matches if m.category == cat]) for r in results if cat in r.categories
        ]
        if not cat_results:
            continue

        label = category_labels.get(cat, cat.replace("_", " ").title())
        lines.append(f"## {label}")
        lines.append("")

        for result, matches in cat_results:
            lines.append(f"### `{result.file}`")
            lines.append("")
            lines.append("| Line | Snippet |")
            lines.append("|------|---------|")
            for m in matches:
                snippet = m.line_content.strip()
                # Escape pipe chars in snippet so table doesn't break
                snippet = snippet.replace("|", "\\|")
                badge = " *(transitive)*" if m.transitive else ""
                lines.append(f"| {m.line} | `{snippet}`{badge} |")
            lines.append("")

        lines.append("---")
        lines.append("")

    if not results:
        lines.append("*No network-capable files found.*")
        lines.append("")

    lines.append("*Generated by [network-footprint](https://github.com/TribeAI/network-footprint)*")
    return "\n".join(lines)
